title:  # your name (or website title) here
logo: "/gm_symbol.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer, Game Designer, Philosopher, Gamer, General Purpose AI Enthusiast
  <br><br>
  Contact email: Rene.Goldmann@rub.de
  <br><br>
  <a href="https://conqueror933.github.io/portfolio/home">Home</a>
  
theme: jekyll-theme-hacker
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
