title: [Rene Goldmann](https://conqueror933.github.io/) # your name (or website title) here
logo: "/gm_symbol.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Portfolio under construction.
  <br><br>
  Insert intelligent joke here.
  <br><br>
  <a href="https://www.linkedin.com/in/rene-g-7064b5179/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-hacker
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
