title: Rene Goldmann # your name (or website title) here
logo: "/gm_symbol.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer, Game Designer, Philosoph, Gamer, Mad Genius, Wizard
  <br>
  "Catch Phrase"
  <br><br>
  Contact email: Rene.Goldmann@rub.de
  <br><br>
  <a href="https://conqueror933.github.io/portfolio">Home</a>
  
theme: jekyll-theme-hacker
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
